
name: pytest-coverage-commentator
on:
  pull_request:
    branches: 
      - '*'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    name: Create test coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Build coverage file
      run: |
        cd src/
        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cache-clear --cov=./ tests/ > pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./src/pytest-coverage.txt
        title: Coverage Report
        badge-title: Coverage
        hide-badge: false
        hide-report: false
        create-new-comment: false
        hide-comment: false
        report-only-changed-files: false
        junitxml-path: ./src/pytest.xml


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Test with pytest
      run: |
        pytest